import 'package:about/models/book_model.dart';

class ApiService {
  static const String baseUrl = 'http://localhost:5000';
  static const String book = 'book';
// 더미데이터
  static const List<dynamic> books = [
    {
      'bookId': 'book1',
      'userId': 'user1',
      'title': '화산귀환',
      'author': '비가',
      'genre': '무협',
      'platform': '시리즈',
      'frstDt': '20230217',
      'lstDt': '20230217',
      'isCompleted': false,
      'islikely': false,
      'readNum': 1411,
      'completedNum': null,
    },
    {
      'bookId': 'book2',
      'userId': 'user1',
      'title': '데뷔 못 하면 죽는 병 걸림',
      'author': '백덕수',
      'genre': '판타지',
      'platform': '카카페',
      'frstDt': '20230217',
      'lstDt': '20230217',
      'isCompleted': false,
      'islikely': false,
      'readNum': 520,
      'completedNum': null,
    },
    {
      'bookId': 'book3',
      'userId': 'user1',
      'title': '내가 키운 S급들',
      'author': '근서',
      'genre': '판타지',
      'platform': '리디',
      'frstDt': '20230217',
      'lstDt': '20230217',
      'isCompleted': true,
      'islikely': false,
      'readNum': 720,
      'completedNum': 720,
    },
    {
      'bookId': 'book3',
      'userId': 'user1',
      'title': '문과라도 안 죄송한 이세계로 감',
      'author': '정수읠',
      'genre': '판타지',
      'platform': '리디',
      'frstDt': '20230217',
      'lstDt': '20230217',
      'isCompleted': false,
      'islikely': false,
      'readNum': 446,
      'completedNum': 490,
    },
    {
      'bookId': 'book1',
      'userId': 'user1',
      'title': '화산귀환',
      'author': '비가',
      'genre': '무협',
      'platform': '시리즈',
      'frstDt': '20230217',
      'lstDt': '20230217',
      'isCompleted': false,
      'islikely': false,
      'readNum': 1411,
      'completedNum': null,
    },
    {
      'bookId': 'book2',
      'userId': 'user1',
      'title': '데뷔 못 하면 죽는 병 걸림',
      'author': '백덕수',
      'genre': '판타지',
      'platform': '카카페',
      'frstDt': '20230217',
      'lstDt': '20230217',
      'isCompleted': false,
      'islikely': false,
      'readNum': 520,
      'completedNum': null,
    },
    {
      'bookId': 'book3',
      'userId': 'user1',
      'title': '내가 키운 S급들',
      'author': '근서',
      'genre': '판타지',
      'platform': '리디',
      'frstDt': '20230217',
      'lstDt': '20230217',
      'isCompleted': true,
      'islikely': false,
      'readNum': 720,
      'completedNum': 720,
    },
    {
      'bookId': 'book3',
      'userId': 'user1',
      'title': '문과라도 안 죄송한 이세계로 감',
      'author': '정수읠',
      'genre': '판타지',
      'platform': '리디',
      'frstDt': '20230217',
      'lstDt': '20230217',
      'isCompleted': false,
      'islikely': false,
      'readNum': 446,
      'completedNum': 490,
    },
    {
      'bookId': 'book1',
      'userId': 'user1',
      'title': '화산귀환',
      'author': '비가',
      'genre': '무협',
      'platform': '시리즈',
      'frstDt': '20230217',
      'lstDt': '20230217',
      'isCompleted': false,
      'islikely': false,
      'readNum': 1411,
      'completedNum': null,
    },
    {
      'bookId': 'book2',
      'userId': 'user1',
      'title': '데뷔 못 하면 죽는 병 걸림',
      'author': '백덕수',
      'genre': '판타지',
      'platform': '카카페',
      'frstDt': '20230217',
      'lstDt': '20230217',
      'isCompleted': false,
      'islikely': false,
      'readNum': 520,
      'completedNum': null,
    },
    {
      'bookId': 'book3',
      'userId': 'user1',
      'title': '내가 키운 S급들',
      'author': '근서',
      'genre': '판타지',
      'platform': '리디',
      'frstDt': '20230217',
      'lstDt': '20230217',
      'isCompleted': true,
      'islikely': false,
      'readNum': 720,
      'completedNum': 720,
    },
    {
      'bookId': 'book3',
      'userId': 'user1',
      'title': '문과라도 안 죄송한 이세계로 감',
      'author': '정수읠',
      'genre': '판타지',
      'platform': '리디',
      'frstDt': '20230217',
      'lstDt': '20230217',
      'isCompleted': false,
      'islikely': false,
      'readNum': 446,
      'completedNum': 490,
    },
    {
      'bookId': 'book1',
      'userId': 'user1',
      'title': '화산귀환',
      'author': '비가',
      'genre': '무협',
      'platform': '시리즈',
      'frstDt': '20230217',
      'lstDt': '20230217',
      'isCompleted': false,
      'islikely': false,
      'readNum': 1411,
      'completedNum': null,
    },
    {
      'bookId': 'book2',
      'userId': 'user1',
      'title': '데뷔 못 하면 죽는 병 걸림',
      'author': '백덕수',
      'genre': '판타지',
      'platform': '카카페',
      'frstDt': '20230217',
      'lstDt': '20230217',
      'isCompleted': false,
      'islikely': false,
      'readNum': 520,
      'completedNum': null,
    },
    {
      'bookId': 'book3',
      'userId': 'user1',
      'title': '내가 키운 S급들',
      'author': '근서',
      'genre': '판타지',
      'platform': '리디',
      'frstDt': '20230217',
      'lstDt': '20230217',
      'isCompleted': true,
      'islikely': false,
      'readNum': 720,
      'completedNum': 720,
    },
    {
      'bookId': 'book3',
      'userId': 'user1',
      'title': '문과라도 안 죄송한 이세계로 감',
      'author': '정수읠',
      'genre': '판타지',
      'platform': '리디',
      'frstDt': '20230217',
      'lstDt': '20230217',
      'isCompleted': false,
      'islikely': false,
      'readNum': 446,
      'completedNum': 490,
    },
    {
      'bookId': 'book1',
      'userId': 'user1',
      'title': '화산귀환',
      'author': '비가',
      'genre': '무협',
      'platform': '시리즈',
      'frstDt': '20230217',
      'lstDt': '20230217',
      'isCompleted': false,
      'islikely': false,
      'readNum': 1411,
      'completedNum': null,
    },
    {
      'bookId': 'book2',
      'userId': 'user1',
      'title': '데뷔 못 하면 죽는 병 걸림',
      'author': '백덕수',
      'genre': '판타지',
      'platform': '카카페',
      'frstDt': '20230217',
      'lstDt': '20230217',
      'isCompleted': false,
      'islikely': false,
      'readNum': 520,
      'completedNum': null,
    },
    {
      'bookId': 'book3',
      'userId': 'user1',
      'title': '내가 키운 S급들',
      'author': '근서',
      'genre': '판타지',
      'platform': '리디',
      'frstDt': '20230217',
      'lstDt': '20230217',
      'isCompleted': true,
      'islikely': false,
      'readNum': 720,
      'completedNum': 720,
    },
    {
      'bookId': 'book3',
      'userId': 'user1',
      'title': '문과라도 안 죄송한 이세계로 감',
      'author': '정수읠',
      'genre': '판타지',
      'platform': '리디',
      'frstDt': '20230217',
      'lstDt': '20230217',
      'isCompleted': false,
      'islikely': false,
      'readNum': 446,
      'completedNum': 490,
    },
  ];
// 더미데이터2
  static const List<dynamic> books2 = [
    {
      'bookId': 'book1',
      'userId': 'user1',
      'title': '화산귀환',
      'author': '비가',
      'genre': '무협',
      'platform': '시리즈',
      'frstDt': '20230217',
      'lstDt': '20230217',
      'isCompleted': false,
      'islikely': false,
      'readNum': 1411,
      'completedNum': null,
    },
  ];

  static Future<List<BookModel>> getUsersBooks(
      {List<String>? condition}) async {
    List<BookModel> bookInstances = [];
    print('getUserBooks');
    if (condition != null) {
      print(condition.map((e) => print(e)));
      print('뭐임');
    }

    final url = Uri.parse('$baseUrl/$book');
    // final response = await http.get(url);

    // if (response.statusCode == 200) {
    //   // print(response.body);

    //   final List<dynamic> books = jsonDecode(response.body);

    for (var book in books) {
      final jsonBook = BookModel.fromJson(book);
      print(jsonBook.title);

      bookInstances.add(BookModel.fromJson(book));
    }
    return bookInstances;
    // }
    throw Error();
  }
}
